DROP TABLE users IF EXISTS;

CREATE TABLE users (
id INTEGER NOT NULL PRIMARY KEY,
username VARCHAR(50) NOT NULL, 
password VARCHAR(50) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL 
);